# server port
server:
  port: 443
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      cookie:
        same-site: Lax
  ssl:
    enable: true
    key-store: classpath:mykeystore.jks
    key-store-password: my123456t
    key-store-type: jks
    key-alias: mykey

#  error:
#    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
#    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부

# thymeleaf / database
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.13.28:1521/EMP
#    username: nsqm
#    password: dongwoo1234
#    url: jdbc:oracle:thin:@175.126.38.80:1521/ORCL
    #url: jdbc:oracle:thin:@localhost:1521/xe
   # url: jdbc:oracle:thin:@CO-NB-21-014.covision.co.kr:1521/xe
    url: jdbc:oracle:thin:@172.16.1.191:1521/xe
    username: c##NSQM
    password: 12345
  datasource2:
      driver-class-name: oracle.jdbc.OracleDriver
      #    url: jdbc:oracle:thin:@192.168.13.28:1521/EMP
      #    username: nsqm
      #    password: dongwoo1234
      #    url: jdbc:oracle:thin:@175.126.38.80:1521/ORCL
      #url: jdbc:oracle:thin:@localhost:1521/xe
      # url: jdbc:oracle:thin:@CO-NB-21-014.covision.co.kr:1521/xe
      url: jdbc:oracle:thin:@172.16.1.191:1521/xe
      username: c##NSQM
      password: 12345
  messages:
    basename: messages
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    enable: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    freemarker:
      cache: false
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
    check-template-location: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hansun126@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # STARTTLS 활성화
          timeout: 5000

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

Logging:
  config: classpath:logback-spring.xml

# Upload File Path Setting
Upload:
  path:
    attach: "D:/SCHEMA/STORAGE/ATTACH"
    excel: "D:/SCHEMA/STORAGE/EXCEL"
    iso: "D:/SCHEMA/STORAGE/ISO"
    audit: "D:/SCHEMA/STORAGE/AUDIT"
    warranty: "D:/SCHEMA/STORAGE/WARRANTY"
    sample: "D:/SCHEMA/STORAGE/SAMPLE"

restfull:
  povis:
    url: "https://fcf98340-8a06-4f69-a8e7-da3fd354095c.mock.pstmn.io"

