# server port
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# thymeleaf
thymeleaf:
  enable: true
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  check-template-location: true

# database
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: C##NSQM
    password: 12345
  messages:
    basename: messages
    encoding: UTF-8


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

