# server port
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#    session:
#      timeout:90m  //1800초
#  error:
#    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
#    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부

# thymeleaf


# database
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.13.28:1521/EMP
#    username: nsqm
#    password: dongwoo1234
    url: jdbc:oracle:thin:@CO-NB-21-014.covision.co.kr:1521/xe
    username: c##schema
    password: 12345
  messages:
    basename: messages
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    enable: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    freemarker:
      cache: false
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
    check-template-location: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

Logging:
  config: classpath:logback-spring.xml

Upload:
  path: "D:/devp/"